// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back.Data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20261006205119_CategoriasBodegasTraslados")]
    partial class CategoriasBodegasTraslados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("back.Models.BodegaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Predeterminada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasFilter("\"Predeterminada\"");

                    b.HasIndex("EmpresaId", "NombreNormalizado")
                        .IsUnique();

                    b.ToTable("BodegaInventario", (string)null);
                });

            modelBuilder.Entity("back.Models.CategoriaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "NombreNormalizado")
                        .IsUnique();

                    b.ToTable("CategoriaInventario", (string)null);
                });

            modelBuilder.Entity("back.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("TelefonoOpcional")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("back.Models.EstadoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "GrupoId", "NombreNormalizado")
                        .IsUnique();

                    b.ToTable("EstadoTarea", (string)null);
                });

            modelBuilder.Entity("back.Models.ExistenciaBodega", b =>
                {
                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("BodegaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.HasKey("EmpresaId", "ProductoId", "BodegaId");

                    b.HasIndex("EmpresaId", "BodegaId");

                    b.ToTable("ExistenciaBodega", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExistenciaBodega_Cantidad", "\"Cantidad\" >= 0");
                        });
                });

            modelBuilder.Entity("back.Models.GrupoTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "NombreNormalizado")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "SupervisorId");

                    b.ToTable("GrupoTrabajo", (string)null);
                });

            modelBuilder.Entity("back.Models.MiembroGrupo", b =>
                {
                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EmpresaId", "GrupoId", "UsuarioId");

                    b.HasIndex("EmpresaId", "UsuarioId");

                    b.ToTable("MiembroGrupo", (string)null);
                });

            modelBuilder.Entity("back.Models.MovimientoInventario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AutorId")
                        .HasColumnType("integer");

                    b.Property<int>("BodegaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cambio")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<decimal>("CambioBodega")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<string>("Cliente")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CorreoAutor")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SaldoAnterior")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<decimal>("SaldoBodegaAnterior")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<decimal>("SaldoBodegaPosterior")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<decimal>("SaldoPosterior")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<string>("SolicitudDatos")
                        .HasColumnType("text");

                    b.Property<Guid?>("SolicitudId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(24, 2)
                        .HasColumnType("numeric(24,2)");

                    b.Property<Guid?>("TrasladoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "BodegaId");

                    b.HasIndex("EmpresaId", "SolicitudId")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "ProductoId", "Id");

                    b.HasIndex("EmpresaId", "ProductoId", "PrestamoId");

                    b.ToTable("MovimientoInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimientoInventario_Bodega", "\"SaldoBodegaAnterior\" >= 0 AND \"SaldoBodegaPosterior\" >= 0 AND \"SaldoBodegaAnterior\" + \"CambioBodega\" = \"SaldoBodegaPosterior\"");

                            t.HasCheckConstraint("CK_MovimientoInventario_Saldos", "\"SaldoAnterior\" >= 0 AND \"SaldoPosterior\" >= 0 AND \"SaldoAnterior\" + \"Cambio\" = \"SaldoPosterior\" AND \"Cantidad\" >= 0");

                            t.HasCheckConstraint("CK_MovimientoInventario_Tipo", "\"Tipo\" IN ('Inicial', 'Entrada', 'Venta', 'Consumo', 'Prestamo', 'DevolucionPrestamo', 'Devolucion', 'Conteo', 'Ajuste', 'TrasladoSalida', 'TrasladoEntrada')");
                        });
                });

            modelBuilder.Entity("back.Models.NotaTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("CorreoAutor")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("TareaId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAutor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AutorId");

                    b.HasIndex("EmpresaId", "TareaId");

                    b.ToTable("NotaTarea", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotaTarea_TipoAutor", "\"TipoAutor\" IN ('Asignado', 'Supervisor')");
                        });
                });

            modelBuilder.Entity("back.Models.PrestamoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodegaOrigenId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int?>("DestinatarioUsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Devuelta")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsExterno")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("FechaPrevista")
                        .HasColumnType("date");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "BodegaOrigenId");

                    b.HasIndex("EmpresaId", "DestinatarioUsuarioId");

                    b.HasIndex("EmpresaId", "ProductoId", "Id");

                    b.ToTable("PrestamoInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrestamoInventario_Cantidades", "\"Cantidad\" > 0 AND \"Devuelta\" >= 0 AND \"Devuelta\" <= \"Cantidad\"");

                            t.HasCheckConstraint("CK_PrestamoInventario_Destinatario", "length(trim(\"Destinatario\")) > 0 AND (NOT \"EsExterno\" OR \"DestinatarioUsuarioId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("back.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsFractions")
                        .HasColumnType("boolean");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("MinimumStock")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Unidad");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CategoriaId");

                    b.HasIndex("EmpresaId", "Code")
                        .IsUnique();

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_Cantidades", "\"Quantity\" >= 0 AND \"MinimumStock\" >= 0 AND (\"AllowsFractions\" OR (trunc(\"Quantity\") = \"Quantity\" AND trunc(\"MinimumStock\") = \"MinimumStock\"))");
                        });
                });

            modelBuilder.Entity("back.Models.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("AutorId")
                        .HasColumnType("integer");

                    b.Property<string>("CorreoAutor")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Id");

                    b.ToTable("RegistroAuditoria", (string)null);
                });

            modelBuilder.Entity("back.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoSistema")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Permisos")
                        .HasColumnType("integer");

                    b.Property<int>("PermisosGrupos")
                        .HasColumnType("integer");

                    b.Property<int>("PermisosTareas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CodigoSistema")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "NombreNormalizado")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("back.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadaEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<bool>("PermitirAutoasignacion")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AsignadoAId");

                    b.HasIndex("EmpresaId", "GrupoId", "EstadoId");

                    b.ToTable("Tarea", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tarea_Autoasignacion", "\"AsignadoAId\" IS NULL OR NOT \"PermitirAutoasignacion\"");
                        });
                });

            modelBuilder.Entity("back.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContraseniaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CorreoNormalizado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CorreoNormalizado")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("back.Models.BodegaInventario", b =>
                {
                    b.HasOne("back.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back.Models.CategoriaInventario", b =>
                {
                    b.HasOne("back.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back.Models.EstadoTarea", b =>
                {
                    b.HasOne("back.Models.GrupoTrabajo", "Grupo")
                        .WithMany("Estados")
                        .HasForeignKey("EmpresaId", "GrupoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("back.Models.ExistenciaBodega", b =>
                {
                    b.HasOne("back.Models.BodegaInventario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "BodegaId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "ProductoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("back.Models.GrupoTrabajo", b =>
                {
                    b.HasOne("back.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Models.Usuario", "Supervisor")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "SupervisorId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("back.Models.MiembroGrupo", b =>
                {
                    b.HasOne("back.Models.GrupoTrabajo", "Grupo")
                        .WithMany("Miembros")
                        .HasForeignKey("EmpresaId", "GrupoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "UsuarioId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back.Models.MovimientoInventario", b =>
                {
                    b.HasOne("back.Models.BodegaInventario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "BodegaId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "ProductoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back.Models.PrestamoInventario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "ProductoId", "PrestamoId")
                        .HasPrincipalKey("EmpresaId", "ProductoId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("back.Models.NotaTarea", b =>
                {
                    b.HasOne("back.Models.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "AutorId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("back.Models.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "TareaId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("back.Models.PrestamoInventario", b =>
                {
                    b.HasOne("back.Models.BodegaInventario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "BodegaOrigenId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "DestinatarioUsuarioId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("back.Models.Product", "Producto")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "ProductoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("back.Models.Product", b =>
                {
                    b.HasOne("back.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Models.CategoriaInventario", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "CategoriaId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("back.Models.RegistroAuditoria", b =>
                {
                    b.HasOne("back.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back.Models.Rol", b =>
                {
                    b.HasOne("back.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("back.Models.Tarea", b =>
                {
                    b.HasOne("back.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Models.Usuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "AsignadoAId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("back.Models.GrupoTrabajo", "Grupo")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "GrupoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back.Models.EstadoTarea", "Estado")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "GrupoId", "EstadoId")
                        .HasPrincipalKey("EmpresaId", "GrupoId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("Estado");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("back.Models.Usuario", b =>
                {
                    b.HasOne("back.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "RolId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("back.Models.GrupoTrabajo", b =>
                {
                    b.Navigation("Estados");

                    b.Navigation("Miembros");
                });
#pragma warning restore 612, 618
        }
    }
}
