using System.Diagnostics;
using System.Net;
using System.Net.Http.Json;
using System.Net.Sockets;
using System.Text.Json;
using back.Data;
using back.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.Configuration;
using Npgsql;

// Prueba real de HTTP/PostgreSQL, en un esquema temporal que se elimina al terminar.
var config = new ConfigurationBuilder().AddUserSecrets<InventoryDbContext>().AddEnvironmentVariables().Build();
var connection = config["DATABASE_URL"] ?? throw new InvalidOperationException("Falta DATABASE_URL en User Secrets o en el entorno.");
// PgBouncer en modo transacción no conserva search_path entre operaciones.
// Para esta prueba aislada se usa la conexión directa del mismo endpoint de Neon.
var sourceConnection = PostgresConnection.Direct(connection);
var schema = "empresa_test_" + Guid.NewGuid().ToString("N");
var connectionBuilder = new NpgsqlConnectionStringBuilder(sourceConnection) { SearchPath = schema };
var backDirectory = Path.GetFullPath("back");
var processes = new List<Process>();
var failures = new List<string>();
var checks = 0;
await using var source = new NpgsqlConnection(sourceConnection);
await source.OpenAsync();
await Sql(source, $"CREATE SCHEMA \"{schema}\"");
try
{
    await using var isolated = new NpgsqlConnection(connectionBuilder.ConnectionString);
    await isolated.OpenAsync();
    await Sql(isolated, $"SET search_path TO \"{schema}\"");
    await using (var schemaCheck = new NpgsqlCommand("SELECT current_schema()", isolated))
    {
        var actual = (string?)await schemaCheck.ExecuteScalarAsync();
        if (actual != schema)
            throw new InvalidOperationException($"La conexión no está aislada (schema actual: {actual ?? "null"}). Se cancelan las pruebas antes de escribir datos.");
    }
    // Simula la tabla creada por la versión anterior con EnsureCreated.
    await Sql(isolated, """
        CREATE TABLE products ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Code" varchar(40) NOT NULL, "Name" varchar(120) NOT NULL, "Quantity" integer NOT NULL,
            "MinimumStock" integer NOT NULL, "UnitPrice" numeric(12,2) NOT NULL, "UpdatedAtUtc" timestamptz NOT NULL);
        INSERT INTO products ("Code", "Name", "Quantity", "MinimumStock", "UnitPrice", "UpdatedAtUtc")
            VALUES ('ANTERIOR', 'Dato de prueba anterior', 1, 0, 1, now());
        """);
    var options = new DbContextOptionsBuilder<InventoryDbContext>();
    PostgresConnection.Configure(options, connectionBuilder.ConnectionString);
    await using (var previous = new InventoryDbContext(options.Options))
        await previous.GetService<IMigrator>().MigrateAsync("20261006004527_EmpresasYUsuarios");
    await using (var oldProducts = new NpgsqlCommand("SELECT count(*) FROM products", isolated))
        Check((long)(await oldProducts.ExecuteScalarAsync())! == 0, "Migración inicial reinicia solo el inventario anterior de prueba");
    // Usuarios y productos de la versión anterior: la migración de roles NO debe borrarlos.
    var hash = new PasswordHasher<Usuario>().HashPassword(new Usuario(), "Migrado123!");
    await using (var seed = new NpgsqlCommand("""
        INSERT INTO "Empresa" ("Nombre", "Telefono", "CreadaEnUtc") VALUES ('Empresa migrada', '5555-0000', now());
        INSERT INTO "Usuario" ("EmpresaId", "Correo", "CorreoNormalizado", "ContraseniaHash", "EsPrincipal", "CreadoEnUtc")
        SELECT e."Id", v.correo, upper(v.correo), @hash, v.principal, now() FROM "Empresa" e
        CROSS JOIN (VALUES ('migrado@example.test', TRUE), ('migrado-miembro@example.test', FALSE)) v(correo, principal);
        INSERT INTO products ("EmpresaId", "Code", "Name", "Quantity", "MinimumStock", "UnitPrice", "UpdatedAtUtc")
        SELECT "Id", 'CONSERVADO', 'Producto conservado', 1, 0, 1, now() FROM "Empresa";
        """, isolated))
    { seed.Parameters.AddWithValue("hash", hash); await seed.ExecuteNonQueryAsync(); }
    var port = FreePort();
    var baseUrl = $"http://localhost:{port}";
    Console.WriteLine($"SERVIDOR DE PRUEBA: {baseUrl} | SCHEMA: {schema}");
    StartServer(port);
    using var ownerA = Client(baseUrl);
    await Ready(ownerA);
    using var migrated = Client(baseUrl);
    await Csrf(migrated);
    var migratedLogin = await OkJson(migrated.PostAsJsonAsync("/api/auth/login", new { correo = "migrado@example.test", contrasenia = "Migrado123!" }));
    Check(migratedLogin.GetProperty("usuario").GetProperty("rol").GetProperty("esAdministrador").GetBoolean(), "Principal anterior migra a Administrador de empresa");
    Check((await OkJson(migrated.GetAsync("/api/products")))[0].GetProperty("code").GetString() == "CONSERVADO", "Migración de roles conserva inventario empresarial");
    using var migratedMember = Client(baseUrl);
    await Csrf(migratedMember);
    var migratedStaff = await OkJson(migratedMember.PostAsJsonAsync("/api/auth/login", new { correo = "migrado-miembro@example.test", contrasenia = "Migrado123!" }));
    Check(!migratedStaff.GetProperty("usuario").GetProperty("rol").GetProperty("esAdministrador").GetBoolean() &&
        (await OkJson(migratedMember.GetAsync("/api/products"))).GetArrayLength() == 1, "Usuario anterior conserva acceso a inventario sin administración");
    Check((await ownerA.GetAsync("/api/products")).StatusCode == HttpStatusCode.Unauthorized, "Inventario requiere login");
    Check((await ownerA.PostAsJsonAsync("/api/auth/register", Registration("Sin CSRF"))).StatusCode == HttpStatusCode.BadRequest, "Registro requiere CSRF");
    await Csrf(ownerA);
    var invalid = await ownerA.PostAsJsonAsync("/api/auth/register", new { nombreEmpresa = " ", correo = "no-es-correo", contrasenia = "123", telefono = "", telefonoOpcional = (string?)null });
    Check(invalid.StatusCode == HttpStatusCode.BadRequest, "Valida registro incompleto");

    var a = await OkJson(ownerA.PostAsJsonAsync("/api/auth/register", Registration("Empresa A")));
    var empresaA = a.GetProperty("empresaActiva").GetProperty("id").GetInt32();
    Check(a.GetProperty("usuario").GetProperty("rol").GetProperty("esAdministrador").GetBoolean(), "Registro crea administrador de empresa");
    Check(a.GetProperty("empresaActiva").GetProperty("telefonoOpcional").ValueKind == JsonValueKind.Null, "Segundo teléfono opcional");
    await Csrf(ownerA);
    Check((await OkJson(ownerA.GetAsync("/api/products"))).GetArrayLength() == 0, "Empresa nueva inicia sin productos de otras empresas");
    var rolesA = (await OkJson(ownerA.GetAsync("/api/roles"))).GetProperty("roles");
    var adminA = rolesA.EnumerateArray().Single(role => role.GetProperty("esAdministrador").GetBoolean()).GetProperty("id").GetInt32();
    var operatorA = rolesA.EnumerateArray().Single(role => !role.GetProperty("esAdministrador").GetBoolean()).GetProperty("id").GetInt32();
    var ownerIdA = a.GetProperty("usuario").GetProperty("id").GetInt32();
    var productA = await OkJson(ownerA.PostAsJsonAsync("/api/products", Product("MISMO", "Producto A", empresaA + 1000)));
    var productIdA = productA.GetProperty("id").GetInt32();
    Check(productA.GetProperty("empresaId").GetInt32() == empresaA, "Empresa del producto se obtiene de la sesión");
    Check((await ownerA.PostAsJsonAsync("/api/products", Product("MISMO", "Duplicado"))).StatusCode == HttpStatusCode.Conflict, "Código único dentro de empresa");
    var addedA = await OkJson(ownerA.PostAsJsonAsync("/api/usuarios", new { correo = "empleado@example.test", contrasenia = "Empleado123!", rolId = operatorA, esPrincipal = true, empresaId = empresaA + 1000 }));
    var employeeId = addedA.GetProperty("id").GetInt32();
    Check(!addedA.GetProperty("rol").GetProperty("esAdministrador").GetBoolean(), "Usuario adicional recibe solo el rol indicado por administrador");
    Check((await ownerA.PostAsJsonAsync("/api/usuarios", new { correo = "EMPLEADO@example.test", contrasenia = "Empleado123!", rolId = operatorA })).StatusCode == HttpStatusCode.Conflict, "Correo duplicado normalizado se rechaza dentro de empresa");

    using var ownerB = Client(baseUrl);
    await Csrf(ownerB);
    var b = await OkJson(ownerB.PostAsJsonAsync("/api/auth/register", Registration("Empresa B", "Admin123!", "5555-5678")));
    var empresaB = b.GetProperty("empresaActiva").GetProperty("id").GetInt32();
    Check(a.GetProperty("usuario").GetProperty("id").GetInt32() != b.GetProperty("usuario").GetProperty("id").GetInt32(), "Mismo correo tiene usuarios independientes por empresa");
    await Csrf(ownerB);
    var rolesB = (await OkJson(ownerB.GetAsync("/api/roles"))).GetProperty("roles");
    var adminB = rolesB.EnumerateArray().Single(role => role.GetProperty("esAdministrador").GetBoolean()).GetProperty("id").GetInt32();
    var operatorB = rolesB.EnumerateArray().Single(role => !role.GetProperty("esAdministrador").GetBoolean()).GetProperty("id").GetInt32();
    Check((await OkJson(ownerB.GetAsync("/api/products"))).GetArrayLength() == 0, "Empresa B no ve productos de A");
    await OkJson(ownerB.PostAsJsonAsync("/api/products", Product("MISMO", "Producto B")));
    await OkJson(ownerB.PostAsJsonAsync("/api/usuarios", new { correo = "empleado@example.test", contrasenia = "OtroEmpleado123!", rolId = operatorB }));
    Check((await ownerB.GetAsync($"/api/products/{productIdA}")).StatusCode == HttpStatusCode.NotFound, "No se puede consultar producto ajeno por ID");
    Check((await ownerB.PutAsJsonAsync($"/api/products/{productIdA}", Product("CAMBIO", "Ajeno"))).StatusCode == HttpStatusCode.NotFound, "No se puede editar producto ajeno");
    Check((await ownerB.DeleteAsync($"/api/products/{productIdA}")).StatusCode == HttpStatusCode.NotFound, "No se puede eliminar producto ajeno");

    using var employee = Client(baseUrl);
    await Csrf(employee);
    var staff = await OkJson(employee.PostAsJsonAsync("/api/auth/login", new { correo = "empleado@example.test", contrasenia = "Empleado123!" }));
    Check(staff.GetProperty("empresas").GetArrayLength() == 1 && staff.GetProperty("empresaActiva").GetProperty("id").GetInt32() == empresaA, "Contraseña de A no permite ingresar a B con el mismo correo");
    await Csrf(employee);
    Check((await employee.PostAsJsonAsync("/api/auth/company", new { empresaId = empresaB })).StatusCode == HttpStatusCode.Forbidden, "Selector no permite una cuenta cuya contraseña no se verificó");
    Check((await employee.GetAsync("/api/usuarios")).StatusCode == HttpStatusCode.Forbidden, "Usuario adicional no lista usuarios");
    Check((await employee.PostAsJsonAsync("/api/usuarios", new { correo = "otro@example.test", contrasenia = "Otro12345!" })).StatusCode == HttpStatusCode.Forbidden, "Solo principal crea usuarios");
    var edited = await OkJson(employee.PutAsJsonAsync($"/api/products/{productIdA}", Product("MISMO", "Producto editado por usuario")));
    Check(edited.GetProperty("name").GetString() == "Producto editado por usuario", "Usuario adicional puede editar inventario de su empresa");
    var temporary = await OkJson(employee.PostAsJsonAsync("/api/products", Product("TEMP", "Temporal")));
    Check((await employee.DeleteAsync("/api/products/" + temporary.GetProperty("id").GetInt32())).StatusCode == HttpStatusCode.NoContent, "Usuario adicional puede registrar y eliminar productos propios");

    using var multiple = Client(baseUrl);
    await Csrf(multiple);
    Check((await multiple.PostAsJsonAsync("/api/auth/login", new { correo = "admin@example.test", contrasenia = "Incorrecta123!" })).StatusCode == HttpStatusCode.Unauthorized, "Login rechaza contraseña incorrecta");
    var choices = await OkJson(multiple.PostAsJsonAsync("/api/auth/login", new { correo = "ADMIN@example.test", contrasenia = "Admin123!" }));
    Check(choices.GetProperty("empresaActiva").ValueKind == JsonValueKind.Null && choices.GetProperty("empresas").GetArrayLength() == 2, "Correo/contraseña repetidos requieren elegir empresa");
    Check((await multiple.GetAsync("/api/products")).StatusCode == HttpStatusCode.Forbidden, "Inventario bloqueado hasta elegir empresa");
    await Csrf(multiple);
    var selected = await OkJson(multiple.PostAsJsonAsync("/api/auth/company", new { empresaId = empresaB }));
    Check(selected.GetProperty("empresaActiva").GetProperty("id").GetInt32() == empresaB, "Selecciona la cuenta empresarial correcta");
    await Csrf(multiple);
    Check((await OkJson(multiple.GetAsync("/api/products")))[0].GetProperty("name").GetString() == "Producto B", "Selección consulta inventario de empresa elegida");

    // Roles del sistema y roles propios en una lista, siempre limitados a su empresa.
    Check(rolesA.GetArrayLength() == 2 && adminA != adminB && operatorA != operatorB, "Roles del sistema tienen identidad independiente por empresa");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{ownerIdA}/rol", new { rolId = operatorA })).StatusCode == HttpStatusCode.Conflict, "No se puede quitar al último administrador");
    Check((await ownerA.PutAsJsonAsync($"/api/roles/{adminA}", Role("Cambiado", "inventario.ver"))).StatusCode == HttpStatusCode.Conflict, "Rol del sistema no se puede editar");
    Check((await ownerA.DeleteAsync($"/api/roles/{operatorA}")).StatusCode == HttpStatusCode.Conflict, "Rol del sistema no se puede eliminar");
    Check((await ownerA.PostAsJsonAsync("/api/roles", Role("Inválido", "empresa.administrar"))).StatusCode == HttpStatusCode.BadRequest, "Rol empresarial no puede inventar permiso de administrador");
    Check((await ownerA.PostAsJsonAsync("/api/roles", Role("Sin lectura", "inventario.editar"))).StatusCode == HttpStatusCode.BadRequest, "Permisos de escritura requieren lectura");
    var readOnly = await OkJson(ownerA.PostAsJsonAsync("/api/roles", Role("Solo consulta", "inventario.ver")));
    var readOnlyId = readOnly.GetProperty("id").GetInt32();
    Check(!readOnly.GetProperty("esSistema").GetBoolean() && !readOnly.GetProperty("esAdministrador").GetBoolean(), "Rol propio nunca obtiene control total por su nombre");
    Check((await ownerA.PostAsJsonAsync("/api/roles", Role("solo consulta", "inventario.ver"))).StatusCode == HttpStatusCode.Conflict, "Nombre de rol único dentro de empresa");
    await OkJson(ownerB.PostAsJsonAsync("/api/roles", Role("Solo consulta", "inventario.ver")));
    var combined = (await OkJson(ownerA.GetAsync("/api/roles"))).GetProperty("roles");
    Check(combined.GetArrayLength() == 3 && combined.EnumerateArray().Any(role => !role.GetProperty("esSistema").GetBoolean()), "Administrador ve roles del sistema y propios juntos, no los de otra empresa");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = adminB })).StatusCode == HttpStatusCode.BadRequest, "No se puede asignar un rol de otra empresa");
    Check((await ownerA.PostAsJsonAsync("/api/usuarios", new { correo = "ajeno@example.test", contrasenia = "Ajeno123!", rolId = operatorB })).StatusCode == HttpStatusCode.BadRequest, "Alta de usuario rechaza rol de otra empresa");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{b.GetProperty("usuario").GetProperty("id").GetInt32()}/rol", new { rolId = adminA })).StatusCode == HttpStatusCode.NotFound, "Administrador no puede cambiar usuario de otra empresa");
    Check((await ownerA.PutAsJsonAsync($"/api/roles/{adminB}", Role("Ajeno", "inventario.ver"))).StatusCode == HttpStatusCode.NotFound, "Administrador no puede editar rol ajeno");
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = readOnlyId }));
    Check((await ownerA.DeleteAsync($"/api/roles/{readOnlyId}")).StatusCode == HttpStatusCode.Conflict, "No se elimina un rol que tiene usuarios asignados");
    Check((await employee.GetAsync("/api/products")).StatusCode == HttpStatusCode.OK, "Solo consulta permite ver inventario con la sesión existente");
    Check((await employee.PostAsJsonAsync("/api/products", Product("PROHIBIDO", "No autorizado"))).StatusCode == HttpStatusCode.Forbidden, "Solo consulta bloquea crear productos en API");
    Check((await employee.PutAsJsonAsync($"/api/products/{productIdA}", Product("MISMO", "No autorizado"))).StatusCode == HttpStatusCode.Forbidden, "Solo consulta bloquea editar productos en API");
    Check((await employee.DeleteAsync($"/api/products/{productIdA}")).StatusCode == HttpStatusCode.Forbidden, "Solo consulta bloquea eliminar productos en API");
    Check((await employee.GetAsync("/api/roles")).StatusCode == HttpStatusCode.Forbidden &&
        (await employee.PostAsJsonAsync("/api/roles", Role("Escalada", "inventario.ver"))).StatusCode == HttpStatusCode.Forbidden, "Usuario sin administración no puede consultar ni crear roles");
    await OkJson(ownerA.PutAsJsonAsync($"/api/roles/{readOnlyId}", Role("Consulta y edición", "inventario.ver", "inventario.editar")));
    Check((await employee.PutAsJsonAsync($"/api/products/{productIdA}", Product("MISMO", "Editado con permiso"))).StatusCode == HttpStatusCode.OK &&
        (await employee.PostAsJsonAsync("/api/products", Product("PROHIBIDO", "No autorizado"))).StatusCode == HttpStatusCode.Forbidden, "Editar rol aplica permisos nuevos sin volver a iniciar sesión");
    var creator = await OkJson(ownerA.PostAsJsonAsync("/api/roles", Role("Solo creación", "inventario.ver", "inventario.crear")));
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = creator.GetProperty("id").GetInt32() }));
    var createdWithRole = await OkJson(employee.PostAsJsonAsync("/api/products", Product("POR-ROL", "Creado con permiso")));
    Check((await employee.PutAsJsonAsync($"/api/products/{productIdA}", Product("MISMO", "No autorizado"))).StatusCode == HttpStatusCode.Forbidden, "Crear no concede editar");
    var deleter = await OkJson(ownerA.PostAsJsonAsync("/api/roles", Role("Solo eliminación", "inventario.ver", "inventario.eliminar")));
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = deleter.GetProperty("id").GetInt32() }));
    Check((await employee.DeleteAsync("/api/products/" + createdWithRole.GetProperty("id").GetInt32())).StatusCode == HttpStatusCode.NoContent &&
        (await employee.PostAsJsonAsync("/api/products", Product("PROHIBIDO", "No autorizado"))).StatusCode == HttpStatusCode.Forbidden, "Eliminar no concede crear");
    var none = await OkJson(ownerA.PostAsJsonAsync("/api/roles", Role("Sin acceso")));
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = none.GetProperty("id").GetInt32() }));
    Check((await employee.GetAsync("/api/products")).StatusCode == HttpStatusCode.Forbidden &&
        (await OkJson(employee.GetAsync("/api/auth/me"))).GetProperty("usuario").GetProperty("rol").GetProperty("permisos").GetArrayLength() == 0, "Rol sin permisos puede entrar pero no ver inventario");
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = adminA }));
    Check((await employee.GetAsync("/api/usuarios")).StatusCode == HttpStatusCode.OK, "Administrador puede delegar control total a otro usuario");
    using var employeeB = Client(baseUrl);
    await Csrf(employeeB);
    await OkJson(employeeB.PostAsJsonAsync("/api/auth/login", new { correo = "empleado@example.test", contrasenia = "OtroEmpleado123!" }));
    Check((await employeeB.GetAsync("/api/usuarios")).StatusCode == HttpStatusCode.Forbidden, "Poder total en A no se hereda por el mismo correo en B");
    Check((await employee.PutAsJsonAsync($"/api/usuarios/{ownerIdA}/rol", new { rolId = operatorA })).StatusCode == HttpStatusCode.OK &&
        (await ownerA.GetAsync("/api/roles")).StatusCode == HttpStatusCode.Forbidden, "Administrador delegado puede quitar poder al anterior y se aplica de inmediato");
    Check((await employee.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = operatorA })).StatusCode == HttpStatusCode.Conflict, "Administrador delegado tampoco puede quitar al último administrador");
    await OkJson(employee.PutAsJsonAsync($"/api/usuarios/{ownerIdA}/rol", new { rolId = adminA }));
    var concurrent = await Task.WhenAll(ownerA.PutAsJsonAsync($"/api/usuarios/{ownerIdA}/rol", new { rolId = operatorA }),
        employee.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = operatorA }));
    Check(concurrent.Count(response => response.StatusCode == HttpStatusCode.OK) == 1 &&
        concurrent.Count(response => response.StatusCode == HttpStatusCode.Conflict) == 1, "Cambios concurrentes conservan al último administrador");
    foreach (var response in concurrent) response.Dispose();
    var aStillAdmin = (await OkJson(ownerA.GetAsync("/api/auth/me"))).GetProperty("usuario").GetProperty("rol").GetProperty("esAdministrador").GetBoolean();
    if (!aStillAdmin) await OkJson(employee.PutAsJsonAsync($"/api/usuarios/{ownerIdA}/rol", new { rolId = adminA }));
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{employeeId}/rol", new { rolId = readOnlyId }));
    var enforced = false;
    try { await Sql(isolated, $"UPDATE \"Usuario\" SET \"RolId\" = {adminB} WHERE \"Id\" = {employeeId}"); }
    catch (PostgresException error) when (error.SqlState == "23503") { enforced = true; }
    Check(enforced, "La base también rechaza asignar un rol de otra empresa");
    var unused = await OkJson(ownerA.PostAsJsonAsync("/api/roles", Role("Temporal")));
    Check((await ownerA.DeleteAsync("/api/roles/" + unused.GetProperty("id").GetInt32())).StatusCode == HttpStatusCode.NoContent, "Se puede eliminar un rol empresarial sin usuarios");

    // Edición y eliminación: únicamente administración, dentro de la misma empresa.
    var editable = await OkJson(ownerA.PostAsJsonAsync("/api/usuarios", new { correo = "editar@example.test", contrasenia = "Original123!", rolId = operatorA }));
    var editableId = editable.GetProperty("id").GetInt32();
    await OkJson(ownerB.PostAsJsonAsync("/api/usuarios", new { correo = "editar@example.test", contrasenia = "Original123!", rolId = operatorB }));
    using var editableSession = Client(baseUrl);
    await Csrf(editableSession);
    await OkJson(editableSession.PostAsJsonAsync("/api/auth/login", new { correo = "editar@example.test", contrasenia = "Original123!" }));
    await Csrf(editableSession);
    await OkJson(editableSession.PostAsJsonAsync("/api/auth/company", new { empresaId = empresaA }));
    using var multiEdit = Client(baseUrl);
    await Csrf(multiEdit);
    await OkJson(multiEdit.PostAsJsonAsync("/api/auth/login", new { correo = "editar@example.test", contrasenia = "Original123!" }));
    await Csrf(multiEdit);
    await OkJson(multiEdit.PostAsJsonAsync("/api/auth/company", new { empresaId = empresaB }));
    await Csrf(multiEdit);
    Check((await employee.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("escalada@example.test", adminA))).StatusCode == HttpStatusCode.Forbidden,
        "Usuario sin administración no puede editar correo, contraseña ni rol");
    Check((await employee.DeleteAsync($"/api/usuarios/{editableId}")).StatusCode == HttpStatusCode.Forbidden,
        "Usuario sin administración no puede eliminar cuentas");
    Check((await ownerB.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("ajeno@example.test", operatorB))).StatusCode == HttpStatusCode.NotFound,
        "Administrador no puede editar cuenta de otra empresa");
    Check((await ownerB.DeleteAsync($"/api/usuarios/{editableId}")).StatusCode == HttpStatusCode.NotFound,
        "Administrador no puede eliminar cuenta de otra empresa");
    Check((await ownerA.PutAsJsonAsync("/api/usuarios/2147483647", UserEdit("ausente@example.test", operatorA))).StatusCode == HttpStatusCode.NotFound &&
        (await ownerA.DeleteAsync("/api/usuarios/2147483647")).StatusCode == HttpStatusCode.NotFound,
        "Edición y eliminación rechazan usuarios inexistentes");
    ownerA.DefaultRequestHeaders.Remove("X-CSRF-TOKEN");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("editar@example.test", operatorA))).StatusCode == HttpStatusCode.BadRequest &&
        (await ownerA.DeleteAsync($"/api/usuarios/{editableId}")).StatusCode == HttpStatusCode.BadRequest,
        "Edición y eliminación requieren protección CSRF");
    await Csrf(ownerA);
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("no-es-correo", operatorA))).StatusCode == HttpStatusCode.BadRequest,
        "Edición valida formato del correo");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("editar@example.test", operatorA, "123"))).StatusCode == HttpStatusCode.BadRequest &&
        (await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("editar@example.test", operatorA, new string('x', 129)))).StatusCode == HttpStatusCode.BadRequest &&
        (await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("editar@example.test", operatorA, "        "))).StatusCode == HttpStatusCode.BadRequest,
        "Nueva contraseña valida longitud y rechaza solo espacios");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("editar@example.test", adminB))).StatusCode == HttpStatusCode.BadRequest,
        "Edición rechaza rol de otra empresa");
    var originalHash = await StoredHash(isolated, editableId);
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("ADMIN@example.test", adminA, "Rechazado123!"))).StatusCode == HttpStatusCode.Conflict &&
        originalHash == await StoredHash(isolated, editableId), "Correo duplicado rechaza toda la edición sin cambiar contraseña");
    var updatedRole = await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", new {
        correo = "editar@example.test", contrasenia = (string?)null, rolId = readOnlyId, empresaId = empresaB, esPrincipal = true }));
    Check(updatedRole.GetProperty("rol").GetProperty("id").GetInt32() == readOnlyId &&
        !updatedRole.GetProperty("rol").GetProperty("esAdministrador").GetBoolean(), "Editar usuario aplica el rol sin aceptar poder adicional enviado por el cliente");
    Check(originalHash == await StoredHash(isolated, editableId), "Contraseña nula conserva exactamente el hash existente");
    Check((await editableSession.GetAsync("/api/products")).StatusCode == HttpStatusCode.OK &&
        (await editableSession.PostAsJsonAsync("/api/products", Product("EDIT-BLOCK", "No permitido"))).StatusCode == HttpStatusCode.Forbidden,
        "Cambiar solo el rol conserva sesión y actualiza permisos inmediatamente");
    await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("editar@example.test", operatorA, "")));
    Check(originalHash == await StoredHash(isolated, editableId), "Contraseña vacía también conserva la actual");
    var resetUser = await OkJson(ownerA.PutAsJsonAsync($"/api/usuarios/{editableId}", UserEdit("actualizado@example.test", readOnlyId, "Renovada123!")));
    var resetHash = await StoredHash(isolated, editableId);
    Check(resetUser.GetProperty("correo").GetString() == "actualizado@example.test" &&
        resetUser.GetProperty("rol").GetProperty("id").GetInt32() == readOnlyId, "Administrador actualiza correo, contraseña y rol juntos");
    var verifier = new PasswordHasher<Usuario>();
    Check(resetHash != originalHash && verifier.VerifyHashedPassword(new Usuario(), resetHash, "Renovada123!") != PasswordVerificationResult.Failed &&
        verifier.VerifyHashedPassword(new Usuario(), resetHash, "Original123!") == PasswordVerificationResult.Failed,
        "Contraseña nueva se guarda como hash y reemplaza a la anterior");
    Check(!resetUser.ToString().Contains("contrasenia", StringComparison.OrdinalIgnoreCase), "Edición nunca devuelve contraseña ni hash");
    Check((await editableSession.GetAsync("/api/auth/me")).StatusCode == HttpStatusCode.Unauthorized,
        "Cambiar credenciales invalida la sesión previa de esa cuenta");
    Check((await multiEdit.PostAsJsonAsync("/api/auth/company", new { empresaId = empresaA })).StatusCode == HttpStatusCode.Forbidden &&
        (await OkJson(multiEdit.GetAsync("/api/auth/me"))).GetProperty("empresas").GetArrayLength() == 1,
        "Selector no permite reutilizar la verificación antigua de una cuenta editada");
    Check((await multiEdit.GetAsync("/api/products")).StatusCode == HttpStatusCode.OK,
        "Editar cuenta de A no invalida cuenta independiente con mismo correo en B");
    using var updatedSession = Client(baseUrl);
    await Csrf(updatedSession);
    Check((await updatedSession.PostAsJsonAsync("/api/auth/login", new { correo = "actualizado@example.test", contrasenia = "Original123!" })).StatusCode == HttpStatusCode.Unauthorized,
        "Contraseña anterior no inicia sesión en la cuenta editada");
    var newLogin = await OkJson(updatedSession.PostAsJsonAsync("/api/auth/login", new { correo = "actualizado@example.test", contrasenia = "Renovada123!" }));
    Check(newLogin.GetProperty("empresaActiva").GetProperty("id").GetInt32() == empresaA,
        "Correo y contraseña nuevos permiten iniciar sesión en la empresa original");
    Check((await ownerA.PutAsJsonAsync($"/api/usuarios/{ownerIdA}", UserEdit("admin@example.test", operatorA))).StatusCode == HttpStatusCode.Conflict,
        "Edición completa tampoco puede quitar al último administrador");
    Check((await ownerA.DeleteAsync($"/api/usuarios/{ownerIdA}")).StatusCode == HttpStatusCode.Conflict,
        "No se puede eliminar al último administrador");
    Check((await ownerA.DeleteAsync($"/api/usuarios/{editableId}")).StatusCode == HttpStatusCode.NoContent &&
        !(await OkJson(ownerA.GetAsync("/api/usuarios"))).EnumerateArray().Any(user => user.GetProperty("id").GetInt32() == editableId),
        "Administrador elimina cuenta y desaparece de su lista");
    Check((await updatedSession.GetAsync("/api/products")).StatusCode == HttpStatusCode.Unauthorized,
        "Cuenta eliminada pierde acceso con cookies anteriores");
    Check((await updatedSession.PostAsJsonAsync("/api/auth/login", new { correo = "actualizado@example.test", contrasenia = "Renovada123!" })).StatusCode == HttpStatusCode.Unauthorized,
        "Cuenta eliminada ya no puede iniciar sesión");
    Check((await OkJson(ownerA.GetAsync("/api/products"))).GetArrayLength() == 1 &&
        (await multiEdit.GetAsync("/api/products")).StatusCode == HttpStatusCode.OK,
        "Eliminar un usuario conserva empresa, inventario y cuentas independientes");

    // Cambios sobre la cuenta propia y borrados simultáneos conservan un administrador.
    using var ownerC = Client(baseUrl);
    await Csrf(ownerC);
    var c = await OkJson(ownerC.PostAsJsonAsync("/api/auth/register", Registration("Empresa C", "AdminC123!")));
    await Csrf(ownerC);
    var ownerIdC = c.GetProperty("usuario").GetProperty("id").GetInt32();
    var empresaC = c.GetProperty("empresaActiva").GetProperty("id").GetInt32();
    var adminC = c.GetProperty("usuario").GetProperty("rol").GetProperty("id").GetInt32();
    var delegateC = await OkJson(ownerC.PostAsJsonAsync("/api/usuarios", new { correo = "delegado-c@example.test", contrasenia = "DelegadoC123!", rolId = adminC }));
    var delegateIdC = delegateC.GetProperty("id").GetInt32();
    await OkJson(ownerC.PutAsJsonAsync($"/api/usuarios/{ownerIdC}", UserEdit("admin-c@example.test", adminC, "CambioC123!")));
    Check((await ownerC.GetAsync("/api/auth/me")).StatusCode == HttpStatusCode.Unauthorized,
        "Administrador que cambia sus propias credenciales debe iniciar sesión otra vez");
    await Csrf(ownerC);
    await OkJson(ownerC.PostAsJsonAsync("/api/auth/login", new { correo = "admin-c@example.test", contrasenia = "CambioC123!" }));
    await Csrf(ownerC);
    using var delegatedC = Client(baseUrl);
    await Csrf(delegatedC);
    await OkJson(delegatedC.PostAsJsonAsync("/api/auth/login", new { correo = "delegado-c@example.test", contrasenia = "DelegadoC123!" }));
    await Csrf(delegatedC);
    var concurrentDelete = await Task.WhenAll(ownerC.DeleteAsync($"/api/usuarios/{ownerIdC}"), delegatedC.DeleteAsync($"/api/usuarios/{delegateIdC}"));
    Check(concurrentDelete.Count(response => response.StatusCode == HttpStatusCode.NoContent) == 1 &&
        concurrentDelete.Count(response => response.StatusCode == HttpStatusCode.Conflict) == 1,
        "Borrados simultáneos nunca dejan una empresa sin administrador");
    var deletedClient = concurrentDelete[0].StatusCode == HttpStatusCode.NoContent ? ownerC : delegatedC;
    var remainingClient = concurrentDelete[0].StatusCode == HttpStatusCode.NoContent ? delegatedC : ownerC;
    Check((await deletedClient.GetAsync("/api/auth/me")).StatusCode == HttpStatusCode.Unauthorized &&
        (await OkJson(remainingClient.GetAsync("/api/usuarios"))).GetArrayLength() == 1,
        "Borrarse con otro administrador cierra la sesión y conserva la administración restante");
    foreach (var response in concurrentDelete) response.Dispose();

    // Una segunda instancia comprueba migración idempotente y cookies entre instancias.
    var port2 = FreePort();
    StartServer(port2);
    using var secondHealth = Client($"http://localhost:{port2}");
    await Ready(secondHealth);
    var afterRestart = await OkJson(ownerA.GetAsync($"http://localhost:{port2}/api/auth/me"));
    Check(afterRestart.GetProperty("empresaActiva").GetProperty("id").GetInt32() == empresaA, "Cookie válida en una segunda instancia");
    Check((await OkJson(ownerA.GetAsync($"http://localhost:{port2}/api/products"))).GetArrayLength() == 1, "Migración posterior conserva productos empresariales");
    Check((await multiple.PostAsync("/api/auth/logout", null)).StatusCode == HttpStatusCode.NoContent, "Cierre de sesión correcto");
    Check((await multiple.GetAsync("/api/products")).StatusCode == HttpStatusCode.Unauthorized, "Logout bloquea acceso posterior");
    await using (var query = new NpgsqlCommand("SELECT \"ContraseniaHash\" FROM \"Usuario\"", isolated))
    await using (var reader = await query.ExecuteReaderAsync())
    {
        var hashed = true;
        while (await reader.ReadAsync()) hashed &= reader.GetString(0).StartsWith("AQAAAA") && reader.GetString(0) != "Admin123!";
        Check(hashed, "Contraseñas persistidas como hash");
    }
    Check(!a.ToString().Contains("contrasenia", StringComparison.OrdinalIgnoreCase), "API no devuelve contraseñas ni hashes");
    Console.WriteLine($"RESULTADO: {checks - failures.Count}/{checks} comprobaciones correctas.");
    if (failures.Count > 0) throw new InvalidOperationException(string.Join("; ", failures));
    if (args.Contains("--preview"))
    {
        Console.WriteLine($"PREVIEW: {baseUrl} | SCHEMA: {schema} | admin@example.test / Admin123! | Enter termina y limpia el esquema.");
        Console.ReadLine();
    }
}
finally
{
    foreach (var process in processes)
    {
        if (!process.HasExited) { process.Kill(entireProcessTree: true); await process.WaitForExitAsync(); }
        process.Dispose();
    }
    NpgsqlConnection.ClearAllPools();
    await using var cleanup = new NpgsqlConnection(sourceConnection);
    await cleanup.OpenAsync();
    await Sql(cleanup, $"DROP SCHEMA \"{schema}\" CASCADE");
    Console.WriteLine("Esquema temporal de pruebas eliminado. Base compartida conservada.");
}

void Check(bool success, string description)
{
    checks++;
    if (!success) failures.Add(description);
    Console.WriteLine($"{(success ? "OK" : "ERROR")}: {description}");
}
void StartServer(int port)
{
    var info = new ProcessStartInfo("dotnet") { WorkingDirectory = backDirectory, UseShellExecute = false, CreateNoWindow = true, RedirectStandardOutput = true, RedirectStandardError = true };
    info.ArgumentList.Add(Path.Combine(backDirectory, "bin", "Release", "net10.0", "back.dll"));
    info.ArgumentList.Add("--urls"); info.ArgumentList.Add($"http://localhost:{port}");
    info.Environment["ASPNETCORE_ENVIRONMENT"] = "Development";
    info.Environment["DATABASE_URL"] = connectionBuilder.ConnectionString;
    info.Environment.Remove("PORT");
    var process = Process.Start(info)!;
    process.OutputDataReceived += (_, data) => { if (data.Data?.Contains("fail:") == true) Console.WriteLine(data.Data); };
    process.ErrorDataReceived += (_, data) => { if (data.Data is not null) Console.WriteLine(data.Data); };
    process.BeginOutputReadLine(); process.BeginErrorReadLine(); processes.Add(process);
}
static object Registration(string name, string password = "Admin123!", string? phone2 = null) => new { nombreEmpresa = name, correo = "admin@example.test", contrasenia = password, telefono = "5555-1234", telefonoOpcional = phone2 };
static object Product(string code, string name, int? empresaId = null) => new { code, name, quantity = 20, minimumStock = 5, unitPrice = 7m, empresaId };
static object Role(string nombre, params string[] permisos) => new { nombre, permisos };
static object UserEdit(string correo, int rolId, string? contrasenia = null) => new { correo, rolId, contrasenia };
static HttpClient Client(string url) => new(new HttpClientHandler { CookieContainer = new CookieContainer(), AllowAutoRedirect = false }) { BaseAddress = new Uri(url) };
static async Task Csrf(HttpClient client)
{
    var token = await OkJson(client.GetAsync("/api/auth/csrf"));
    client.DefaultRequestHeaders.Remove("X-CSRF-TOKEN");
    client.DefaultRequestHeaders.Add("X-CSRF-TOKEN", token.GetProperty("token").GetString());
}
static async Task<JsonElement> OkJson(Task<HttpResponseMessage> request)
{
    using var response = await request;
    var text = await response.Content.ReadAsStringAsync();
    if (!response.IsSuccessStatusCode) throw new InvalidOperationException($"HTTP {(int)response.StatusCode}: {text}");
    return JsonDocument.Parse(text).RootElement.Clone();
}
async Task Ready(HttpClient client)
{
    for (var retry = 0; retry < 60; retry++)
    {
        if (processes.Any(process => process.HasExited)) throw new InvalidOperationException("El backend terminó durante el arranque.");
        try { if ((await client.GetAsync("/health")).IsSuccessStatusCode) return; } catch (HttpRequestException) { }
        await Task.Delay(500);
    }
    throw new TimeoutException("El backend no inició.");
}
static int FreePort() { var listener = new TcpListener(IPAddress.Loopback, 0); listener.Start(); var port = ((IPEndPoint)listener.LocalEndpoint).Port; listener.Stop(); return port; }
static async Task Sql(NpgsqlConnection connection, string sql) { await using var command = new NpgsqlCommand(sql, connection); await command.ExecuteNonQueryAsync(); }
static async Task<string> StoredHash(NpgsqlConnection connection, int usuarioId)
{
    await using var command = new NpgsqlCommand("SELECT \"ContraseniaHash\" FROM \"Usuario\" WHERE \"Id\" = @id", connection);
    command.Parameters.AddWithValue("id", usuarioId);
    return (string)(await command.ExecuteScalarAsync())!;
}
